{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: atlas-order
spec:
  ingressClassName: nginx
  rules:
    - host: atlas-order.local
      http:
        paths:
          - path: /api/v1/orders
            pathType: Prefix
            backend:
              service:
                name: atlas-order
                port:
                  number: {{ .Values.service.port }}
{{- end }}