server:
  port: ${ATLAS_SEARCH_PORT}

spring:
  application:
    name: atlas-search

  elasticsearch:
    uris: ${ELASTIC_SEARCH_URL}

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASS}

management:
  tracing:
    sampling:
      probability: 1.0

  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: ${ATLAS_OPENTELEMETRY_OTLP_URL}

    metrics:
      export:
        otlp:
          endpoint: ${ATLAS_METRICS_OTLP_URL}

  endpoints:
    web:
      exposure:
        include: health,info,metrics,beans,prometheus

springdoc:
  swagger-ui:
    path: /swagger-ui.html