image:
  repository: atlas-catalog
  tag: "1.0"

replicaCount: 1

service:
  type: ClusterIP
  port: 8201

database:
  url: "jdbc:postgresql://atlas-postgres:5432/afa-atlas-commerce-catalog-test"
  user: "postgres"

keycloak:
  realm:
    host: "http://host.docker.internal:8080/realms/atlas"

redis:
  host: "atlas-redis"
  port: 6379

mongodb:
  host: "mongodb://atlas-mongodb:27017/atlas-catalog"

rabbit:
  host: "atlas-rabbitmq"
  port: 5672
  user: "atlas"

s3:
  host: "http://host.docker.internal:9100"
  user: "minioadmin"
  bucket:
    url: "http://localhost:9100/atlas-products"

resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "1000m"

ingress:
  enabled: true