apiVersion: apps/v1
kind: Deployment

metadata:
  name: atlas-search

spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 2

  selector:
    matchLabels:
      app: atlas-search

  template:
    metadata:
      labels:
        app: atlas-search

    spec:
      containers:
        - name: atlas-search
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Never

          ports:
            - containerPort: {{ .Values.service.port }}

          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Xms128m -Xmx256m"

          envFrom:
            - configMapRef:
                name: atlas-search-config

            - secretRef:
                name: atlas-search-secret

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.service.port }}
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.service.port }}
            initialDelaySeconds: 45
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3