apiVersion: v1
kind: Secret

metadata:
  name: atlas-search-secret

type: Opaque

stringData:
  ATLAS_RABBITMQ_PASS: "{{ .Values.rabbitmq.password }}"
  RABBITMQ_PASSWORD: "{{ .Values.rabbitmq.password }}"
  RABBITMQ_PASS: "{{ .Values.rabbitmq.password }}"
