server:
  port: 0

spring:
  application:
    name: atlas-order-test

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/atlas

  flyway:
    enabled: true
    locations: classpath:db/migration

  datasource:
    url: jdbc:postgresql://localhost:5432/afa-atlas-commerce-order-test
    username: postgres
    password: postgres

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

  rabbitmq:
    host: localhost
    port: 5672
    username: atlas
    password: atlas
    listener:
      simple:
        auto-startup: false
      direct:
        auto-startup: false

clients:
  catalog:
    url: http://localhost:8201

atlas:
  observability:
    enabled: true
  crypto:
    enabled: true
    secret: 12345678901234567890123456789012