apiVersion: v1
kind: ConfigMap

metadata:
  name: atlas-catalog-config

data:
  ATLAS_CATALOG_PORT: "{{ .Values.service.port }}"

  ATLAS_CATALOG_DATABASE_URL: "{{ .Values.database.url }}"

  ATLAS_CATALOG_DATABASE_USER: "{{ .Values.database.user }}"

  ATLAS_KEYCLOACK_REALM_HOST: "{{ .Values.keycloak.realm.host }}"

  ATLAS_REDIS_HOST:  "{{ .Values.redis.host }}"
  ATLAS_REDIS_PORT: "{{ .Values.redis.port }}"

  ATLAS_MONGODB_HOST: "{{ .Values.mongodb.host }}"

  ATLAS_RABBITMQ_HOST: "{{ .Values.rabbit.host }}"
  ATLAS_RABBITMQ_PORT: "{{ .Values.rabbit.port }}"
  ATLAS_RABBITMQ_USER: "{{ .Values.rabbit.user }}"

  S3_HOST: "{{ .Values.s3.host }}"
  S3_USER: "{{ .Values.s3.user }}"
  S3_BUCKET_URL: "{{ .Values.s3.bucket.url }}"