apiVersion: v1
kind: Secret

metadata:
  name: atlas-catalog-secret

type: Opaque

stringData:
  ATLAS_CATALOG_DATABASE_PASS: "{{ .Values.database.password }}"
  ATLAS_RABBITMQ_PASS: "{{ .Values.rabbit.password }}"
  S3_PASSWORD: "{{ .Values.s3.password }}"