server:
  port: ${ATLAS_GATEWAY_PORT}

debug: false

spring:
  application:
    name: atlas-gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ATLAS_KEYCLOACK_REALM_HOST}

  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - AddResponseHeader=X-Gateway, atlas-gateway

          routes:
            - id: atlas-catalog
              uri: ${ATLAS_CATALOG_HOST}
              predicates:
                - Path=/api/v1/products/**

            - id: atlas-search
              uri: ${ATLAS_SEARCH_HOST}
              predicates:
                - Path=/api/v1/search/**

            - id: atlas-order
              uri: ${ATLAS_ORDER_HOST}
              predicates:
                - Path=/api/v1/orders/**

            - id: atlas-customers
              uri: ${ATLAS_ORDER_HOST}
              predicates:
                - Path=/api/v1/customers/**

management:
  endpoint:
    prometheus:
      access: unrestricted

  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

  prometheus:
    metrics:
      export:
        enabled: true

  otlp:
    metrics:
      export:
        enabled: false

  tracing:
    sampling:
      probability: 1.0

  opentelemetry:
    resource-attributes:
      service.name: atlas-gateway

    tracing:
      export:
        otlp:
          endpoint: ${ATLAS_TRACING_OTLP_URL}
