apiVersion: v1
kind: ConfigMap

metadata:
  name: atlas-analytics-config

data:
  ATLAS_ANALYTICS_PORT: "{{ .Values.service.port }}"

  ATLAS_ANALYTICS_DATABASE_URL: "{{ .Values.database.url }}"
  ATLAS_ANALYTICS_DATABASE_USER: "{{ .Values.database.user }}"

  ATLAS_KAFKA_URL: "{{ .Values.kafka.url }}"