apiVersion: apps/v1
kind: Deployment

metadata:
  name: atlas-analytics

spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 2

  selector:
    matchLabels:
      app: atlas-analytics

  template:
    metadata:
      labels:
        app: atlas-analytics

    spec:
      containers:
        - name: atlas-analytics
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Never

          ports:
            - containerPort: {{ .Values.service.port }}

          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Xms128m -Xmx256m"

          envFrom:
            - configMapRef:
                name: atlas-analytics-config

            - secretRef:
                name: atlas-analytics-secret

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: {{ .Values.service.port }}
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: {{ .Values.service.port }}
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
