apiVersion: v1
kind: Service
metadata:
  name: atlas-elasticsearch
spec:
  ports:
    - port: 9200
      targetPort: 9200
  selector:
    app: atlas-elasticsearch
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: atlas-elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: atlas-elasticsearch
  template:
    metadata:
      labels:
        app: atlas-elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: elasticsearch:9.0.3
          ports:
            - containerPort: 9200
          env:
            - name: discovery.type
              value: single-node
            - name: xpack.security.enabled
              value: "false"
            - name: ES_JAVA_OPTS
              value: "-Xms512m -Xmx512m"