apiVersion: v1
kind: Service
metadata:
  name: atlas-mongodb
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: atlas-mongodb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: atlas-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: atlas-mongodb
  template:
    metadata:
      labels:
        app: atlas-mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:8
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: atlas
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: atlas