apiVersion: v1
kind: Service
metadata:
  name: atlas-redis
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: atlas-redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: atlas-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: atlas-redis
  template:
    metadata:
      labels:
        app: atlas-redis
    spec:
      containers:
        - name: redis
          image: redis:8
          ports:
            - containerPort: 6379